### Import functionality from files

In [1]:
from src.wacc import *

### Download necessary data

In [2]:
download_all()

RiskFreeRates
1.814s
InflationRates
0.693s
CorporateBonds
0.715s
TreasuryBonds
1.568s
CompanyData
1.727s

### Load risk-free rates

In [3]:
rfr = RiskFreeRates.load_data()
display(rfr)

Year
1969    0.060385
1970    0.069259
1971    0.062446
1972    0.058635
1973    0.085347
1974    0.097256
1975    0.102500
1976    0.106809
1977    0.097256
1978    0.089936
1979    0.103340
1980    0.129969
1981    0.155625
1982    0.144900
1983    0.139556
1984    0.138489
1985    0.154013
1986    0.138489
1987    0.132628
1988    0.133693
1989    0.133160
1990    0.124342
1991    0.096104
1992    0.091398
1993    0.067916
1994    0.102920
1995    0.084251
1996    0.074581
1997    0.062333
1998    0.049137
1999    0.068506
2000    0.056200
2001    0.059014
2002    0.054678
2003    0.058402
2004    0.053003
2005    0.054180
2006    0.057777
2007    0.063040
2008    0.042601
2009    0.055480
2010    0.056321
2011    0.038616
2012    0.032535
2013    0.032551
2014    0.029860
2015    0.028723
2016    0.028186
2017    0.025997
2018    0.024458
2019    0.012056
2020    0.009784
2021    0.016155
2022    0.035825
2023    0.042308
2024    0.043595
2025    0.047747
Name: 10Y, dtype: float64

### Load inflation rates

In [4]:
inf = InflationRates.load_data()
display(inf)

Year
1958    0.014
1959    0.024
1960    0.044
1961    0.007
1962    0.000
        ...
2021    0.035
2022    0.079
2023    0.041
2024    0.024
2025    0.036
Name: Inflation, Length: 68, dtype: float64

### Load market returns

In [5]:
ret = MarketReturns.load_data()
display(ret)

Year
1958    0.189000
1959    0.443000
1960   -0.062000
1961    0.116000
1962    0.042000
          ...
2021    0.152305
2022    0.004114
2023    0.070293
2024    0.174130
2025    0.076612
Name: Stock accumulation index, Length: 68, dtype: float64

### Load corporate bonds

In [6]:
cb = CorporateBonds.load_data()
display(cb)

            7Y Effective Tenor  7Y Yield  10Y Effective Tenor  10Y Yield
Date
2025-08-31                6.87      4.92                 8.80       5.13
2025-09-30                6.86      5.03                 8.74       5.18
2025-10-31                6.86      5.08                 8.70       5.23
2025-11-30                6.85      5.36                 8.66       5.50
2025-12-31                6.84      5.50                 8.61       5.64
2026-01-31                6.83      5.55                 8.57       5.67
2026-02-28                6.82      5.50                 8.50       5.62
2026-03-31                6.80      6.02                 8.48       6.11
2026-04-30                6.78      5.99                 8.44       6.07
2026-05-31                6.77      5.72                 8.41       5.81
2026-06-30                6.75      5.52                 8.37       5.61
2026-07-31                6.73      5.70                 8.33       5.80

In [7]:
start_date = cb.index[0]
end_date = cb.index[-1]

print(start_date)
print(end_date)

2025-08-31 00:00:00
2026-07-31 00:00:00

### Load treasury bonds

In [8]:
tb_mat, tb_yld = TreasuryBonds.load_data(start_date, end_date)

In [9]:
display(tb_mat)

,Treasury Bond 158 1.25% 21-May-2032,Treasury Bond 165 1.75% 21-Nov-2032,Treasury Bond 140 4.50% 21-Apr-2033,Treasury Bond 166 3.00% 21-Nov-2033,Treasury Bond 167 3.75% 21-May-2034,Treasury Bond 170 4.25% 21-Jun-2034,Treasury Bond 168 3.50% 21-Dec-2034,Treasury Bond 145 2.75% 21-Jun-2035,Treasury Bond 171 4.25% 21-Dec-2035,Treasury Bond 172 4.25% 21-Mar-2036,Treasury Bond 175 5.00% 21-Jun-2036,Treasury Bond 173 4.25% 21-Oct-2036,Treasury Bond 144 3.75% 21-Apr-2037,Treasury Bond 174 4.75% 21-Oct-2037,Treasury Bond 147 3.25% 21-Jun-2039,Treasury Bond 156 2.75% 21-May-2041,Treasury Bond 150 3.00% 21-Mar-2047,Treasury Bond 162 1.75% 21-Jun-2051
Date,,,,,,,,,,,,,,,,,,
2025-08-31,6.721424,7.225188,7.639185,8.225129,8.721249,8.806134,9.307229,9.806074,10.307194,10.554415,NaN,11.140315,11.639217,NaN,13.806134,15.721372,21.554286,25.806206
2025-09-30,6.639288,7.143053,7.557043,8.142988,8.639102,8.723987,9.225082,9.723923,10.225044,10.472279,NaN,11.058179,11.557077,NaN,13.723987,15.639233,21.472143,25.724064
2025-10-31,6.554415,7.058179,7.472163,8.058108,8.554217,8.639102,9.140197,9.639034,10.140154,10.387406,NaN,10.973306,11.472199,NaN,13.639102,15.554357,21.387262,25.639185
2025-11-30,6.472279,6.976044,7.390021,7.975966,8.472070,8.556955,9.058050,9.556883,10.058003,10.305270,NaN,10.891170,11.390059,NaN,13.556955,15.472218,21.305119,25.557043
2025-12-31,6.387406,6.891170,7.305141,7.891086,8.387185,8.472070,8.973165,9.471994,9.973114,10.220397,NaN,10.806297,11.305181,NaN,13.472070,15.387341,21.220238,25.472163
2026-01-31,6.301916,6.805632,7.219713,7.805613,8.301795,8.386675,8.887740,9.386637,9.887733,10.134893,NaN,10.720757,11.219713,11.720739,13.386661,15.301848,21.134785,25.386689
2026-02-28,6.225264,6.728979,7.143053,7.728953,8.225129,8.310009,8.811074,9.309967,9.811062,10.058238,NaN,10.644102,11.143053,11.644079,13.309994,15.225188,21.058121,25.310025
2026-03-31,6.140399,6.644114,7.058179,7.644079,8.140249,8.225129,8.726194,9.225082,9.726177,9.973370,NaN,10.559233,11.058179,11.559206,13.225112,15.140315,20.973242,25.225147
2026-04-30,6.058271,6.561987,6.976044,7.561944,8.058108,8.142988,8.644052,9.142935,9.644031,9.891239,NaN,10.477103,10.976044,11.477070,13.142969,15.058179,20.891101,25.143008
2026-05-31,5.973406,6.477122,6.891170,7.477070,7.973228,8.058108,8.559172,9.058050,9.559146,9.806371,10.058238,10.392235,10.891170,11.392197,13.058087,14.973306,20.806223,25.058130
2026-06-30,5.891279,6.394994,6.809035,7.394935,7.891086,7.975966,8.477031,8.975904,9.476999,9.724241,9.976108,10.310105,10.809035,11.310062,12.975944,14.891170,20.724082,24.975990
2026-07-31,5.806414,6.310129,6.724162,7.310062,7.806206,7.891086,8.392151,8.891019,9.392114,9.639373,9.891239,10.225236,10.724162,11.225188,12.891062,14.806297,20.639203,24.891112

In [10]:
display(tb_yld)

,Treasury Bond 158 1.25% 21-May-2032,Treasury Bond 165 1.75% 21-Nov-2032,Treasury Bond 140 4.50% 21-Apr-2033,Treasury Bond 166 3.00% 21-Nov-2033,Treasury Bond 167 3.75% 21-May-2034,Treasury Bond 170 4.25% 21-Jun-2034,Treasury Bond 168 3.50% 21-Dec-2034,Treasury Bond 145 2.75% 21-Jun-2035,Treasury Bond 171 4.25% 21-Dec-2035,Treasury Bond 172 4.25% 21-Mar-2036,Treasury Bond 175 5.00% 21-Jun-2036,Treasury Bond 173 4.25% 21-Oct-2036,Treasury Bond 144 3.75% 21-Apr-2037,Treasury Bond 174 4.75% 21-Oct-2037,Treasury Bond 147 3.25% 21-Jun-2039,Treasury Bond 156 2.75% 21-May-2041,Treasury Bond 150 3.00% 21-Mar-2047,Treasury Bond 162 1.75% 21-Jun-2051
Date,,,,,,,,,,,,,,,,,,
2025-08-31,3.886,3.966,4.001,4.095,4.15,4.151,4.213,4.274,4.29,4.309,None,4.351,4.391,None,4.534,4.65,4.896,5.036
2025-09-30,3.948,4.021,4.052,4.135,4.184,4.186,4.243,4.297,4.316,4.335,None,4.376,4.414,None,4.54,4.65,4.879,4.987
2025-10-31,3.952,4.016,4.048,4.122,4.172,4.176,4.229,4.279,4.295,4.31,None,4.35,4.389,None,4.517,4.619,4.849,4.957
2025-11-30,4.221,4.281,4.308,4.376,4.416,4.418,4.462,4.501,4.513,4.528,None,4.564,4.599,None,4.719,4.813,5.018,5.117
2025-12-31,4.449,4.509,4.529,4.592,4.636,4.635,4.684,4.729,4.74,4.757,None,4.786,4.82,None,4.924,4.995,5.176,5.246
2026-01-31,4.51,4.568,4.587,4.654,4.695,4.697,4.74,4.783,4.794,4.805,None,4.836,4.869,4.886,4.973,5.047,5.231,5.295
2026-02-28,4.384,4.434,4.454,4.509,4.546,4.548,4.588,4.627,4.639,4.649,None,4.677,4.703,4.721,4.806,4.886,5.079,5.164
2026-03-31,4.759,4.797,4.816,4.859,4.89,4.892,4.924,4.953,4.963,4.971,None,4.994,5.018,5.03,5.098,5.159,5.326,5.383
2026-04-30,4.859,4.892,4.908,4.949,4.98,4.984,5.012,5.04,5.055,5.063,None,5.086,5.11,5.122,5.189,5.251,5.414,5.469
2026-05-31,4.58,4.624,4.643,4.688,4.725,4.732,4.766,4.802,4.819,4.83,4.844,4.857,4.883,4.896,4.981,5.053,5.249,5.332
2026-06-30,4.464,4.51,4.531,4.578,4.615,4.621,4.656,4.691,4.711,4.722,4.736,4.748,4.775,4.793,4.888,4.973,5.176,5.273
2026-07-31,4.629,4.679,4.705,4.759,4.8,4.806,4.85,4.889,4.91,4.926,4.94,4.954,4.981,4.999,5.09,5.176,5.378,5.48

### Calculate market risk premiums using three approaches

In [11]:
mrp = MarketRiskPremium(rfr, ret, inf)

mrp_i = mrp.ibbotson_approach()
print(f"Ibbotson Approach: {mrp_i:.4f}")

mrp_w = mrp.wright_approach(0.028)
print(f"Wright Approach: {mrp_w:.4f}")

mrp_d = mrp.damodaran_approach()
print(f"Damodaran Approach: {mrp_d:.4f}")

avg_mrp = (mrp_i + mrp_w + mrp_d) / 3
print(f"Average MRP: {avg_mrp:.4f}")

Ibbotson Approach: 0.0484
Wright Approach: 0.0636
Damodaran Approach: 0.0431
Average MRP: 0.0517

### Instantiate cost of equity and cost of debt

In [12]:
coe = CostOfEquity(rfr, [mrp_i, mrp_w, mrp_d])
cod = CostOfDebt(cb, tb_mat, tb_yld)

### Pick a listed asset

In [13]:
pub_company = "JB Hi-Fi"
period = "10Y"
interval = "1wk"

jb = PublicCompany(pub_company)

jb_data = jb.get_data(period, interval)
display(jb_data)

{'Symbol': 'JBH.AX',
 'Industry': 'Specialty Retail',
 'Equity Beta': 1.0193273642589022,
 'Asset Beta': 0.783380809727116,
 'Gearing Ratio': 0.300832088756134,
 'Debt to Equity Ratio': 0.43027158986878244}

### Calculate cost of equity and cost of debt

In [14]:
coe_jb = coe.get_coe(jb_data["Equity Beta"])
print(f"Cost of Equity: {coe_jb * 100:.4f}%")

cod_jb = cod.get_cod()
print(f"Cost of Debt: {cod_jb * 100:.4f}%")

wacc_jb = CalculateWACC(coe_jb, cod_jb, jb_data["Gearing Ratio"])

Cost of Equity: 10.0428%
Cost of Debt: 5.7657%

### Get All Ordinaries companies

In [15]:
asx_companies = CompanyData.get_data()
display(asx_companies)

,Symbol,Company Name,Industry
0,10X.AX,EXULTANT MINING LIMITED,Materials
1,14D.AX,1414 DEGREES LIMITED,Capital Goods
2,1AD.AX,ADALTA LIMITED,"Pharmaceuticals, Biotechnology & Life Sciences"
3,1AE.AX,AURORA ENERGY METALS LIMITED,Materials
4,1AI.AX,ALGORAE PHARMACEUTICALS LIMITED,"Pharmaceuticals, Biotechnology & Life Sciences"
...,...,...,...
1810,ZLD.AX,ZELIRA THERAPEUTICS LIMITED,"Pharmaceuticals, Biotechnology & Life Sciences"
1811,ZMI.AX,ZINC OF IRELAND LIMITED,Materials
1812,ZMM.AX,ZIMI LIMITED,Technology Hardware & Equipment
1813,ZNC.AX,ZENITH MINERALS LIMITED,Materials
1814,ZNO.AX,ZOONO GROUP LIMITED,Materials

### Pick private company

In [16]:
priv_company = "Alinta Energy"
priv_industry = "Utilities"
alinta_gearing = 0.649
alinta_de_ratio = alinta_gearing / (1 - alinta_gearing)

alinta = PrivateCompany(priv_company, priv_industry, alinta_de_ratio, asx_companies)

### Find comparables

In [17]:
comparables = alinta.get_comparables(period, interval)
display(comparables)

,Symbol,Industry,Equity Beta,Asset Beta,Gearing Ratio,Debt to Equity Ratio
0,AGL.AX,Utilities—Independent Power Producers,0.541871,0.366994,0.405021,0.680733
1,CCE.AX,Utilities—Renewable,0.004278,0.003615,0.207507,0.261841
2,CEN.AX,Utilities—Renewable,0.518072,0.367835,0.368478,0.583477
3,GNE.AX,Utilities—Independent Power Producers,0.504504,0.373586,0.333610,0.500622
4,LPE.AX,Utilities—Regulated Electric,0.796518,0.620017,0.289103,0.406673
5,MCY.AX,Utilities—Renewable,0.302303,0.227503,0.319586,0.469694
6,MEZ.AX,Utilities—Renewable,0.469512,0.410738,0.169725,0.204420
7,ORG.AX,Utilities—Diversified,1.179946,0.879459,0.328004,0.488105

### Calculate asset beta

In [18]:
alinta_asset_beta = alinta.get_asset_beta(comparables)
print(alinta_asset_beta)

0.406218409025891

### Calculate equity beta

In [19]:
alinta_equity_beta = alinta.get_equity_beta(alinta_asset_beta)
print(alinta_equity_beta)

0.931987705950285

### Calculate cost of equity and cost of debt

In [20]:
coe_alinta = coe.get_coe(alinta_equity_beta)
print(f"Cost of Equity: {coe_alinta * 100:.4f}%")

cod_alinta = cod.get_cod()
print(f"Cost of Debt: {cod_alinta * 100:.4f}%")

wacc_alinta = CalculateWACC(coe_alinta, cod_alinta, alinta_gearing, 0.3)

Cost of Equity: 9.5914%
Cost of Debt: 5.7657%

### Summary

In [21]:
import pandas as pd

def get_results(
    company: str,
    equity_beta: float,
    asset_beta: float,
    gearing: float,
    de_ratio: float,
    coe: float,
    cod: float,
    wacc_pre_tax: float,
    wacc_vanilla: float,
    wacc_post_tax: float
):
    return {
        "Company": company,
        "Equity Beta": equity_beta,
        "Asset Beta": asset_beta,
        "Gearing Ratio": gearing,
        "Debt to Equity Ratio": de_ratio,
        "Cost of Equity (%)": coe * 100,
        "Cost of Debt (%)": cod * 100,
        "Pre Tax WACC (%)": wacc_pre_tax * 100,
        "Vanilla WACC (%)": wacc_vanilla * 100,
        "Post Tax WACC (%)": wacc_post_tax * 100,
    }

jb_results = get_results(
    pub_company,
    jb_data["Equity Beta"],
    jb_data["Asset Beta"],
    jb_data["Gearing Ratio"],
    jb_data["Debt to Equity Ratio"],
    coe_jb,
    cod_jb,
    wacc_jb.pre_tax(),
    wacc_jb.vanilla(),
    wacc_jb.post_tax()
)

alinta_results = get_results(
    priv_company,
    alinta_equity_beta,
    alinta_asset_beta,
    alinta_gearing,
    alinta_de_ratio,
    coe_alinta,
    cod_alinta,
    wacc_alinta.pre_tax(),
    wacc_alinta.vanilla(),
    wacc_alinta.post_tax()
)

df = pd.DataFrame([jb_results, alinta_results])

display(df)

,Company,Equity Beta,Asset Beta,Gearing Ratio,Debt to Equity Ratio,Cost of Equity (%),Cost of Debt (%),Pre Tax WACC (%),Vanilla WACC (%),Post Tax WACC (%)
0,JB Hi-Fi,1.019327,0.783381,0.300832,0.430272,10.042798,5.765694,11.765366,8.756108,8.235756
1,Alinta Energy,0.931988,0.406218,0.649000,1.849003,9.591406,5.765694,8.551340,7.108519,5.985938